FROM tomcat:7.0-jre7
MAINTAINER Darius Jazayeri <djazayeri@thoughtworks.com>

COPY openmrs*.war /usr/local/tomcat/webapps/
COPY openmrs-runtime.properties /usr/local/tomcat/openmrs-runtime.properties
